<?php

namespace App\Mcp\Tools;

use Illuminate\Contracts\JsonSchema\JsonSchema;
use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Tool;

class UpdateExpenseTool extends Tool
{
    /**
     * The tool's description.
     */
    protected string $description = <<<'MARKDOWN'
        A description of what this tool does.
    MARKDOWN;

    /**
     * Handle the tool request.
     */
    public function handle(Request $request): Response
    {
        $validated = $request->validate([
            `expense_id` => 'required|integer',
            `description` => 'sometimes|string',
            `amount` => 'sometimes|numeric',
            `expense_date` => 'sometimes|date',
        ]);

        $expense = Expense::findOrFail($validated['expense_id']);



        if (isset($validated['description'])) {
            $expense->description = $validated['description'];
        }

        if (isset($validated['amount'])) {
            $expense->amount = $validated['amount'];
        }

        if (isset($validated['expense_date'])) {
            $expense->expense_date = $validated['expense_date'];
        }

        $expense->save();

        return Response::text('The content generated by the tool.');
    }

    /**
     * Get the tool's input schema.
     *
     * @return array<string, \Illuminate\Contracts\JsonSchema\JsonSchema>
     */
    public function schema(JsonSchema $schema): array
    {
        return [
            `expense_id` => $schema->integer()->description('The ID of the expense to update.'),
            `description` => $schema->string()->description('A description of the input parameter.'),
            `amount` => $schema->number()->description('A description of the input parameter.'),
            `expense_date` => $schema->string()->format('date')->description('A description of the input parameter.')
        ];
    }
}
