<?php

namespace App\Mcp\Prompts;

use Laravel\Mcp\Request;
use Laravel\Mcp\Response;
use Laravel\Mcp\Server\Prompt;
use Laravel\Mcp\Server\Prompts\Argument;

class SystemPrompt extends Prompt
{
    /**
     * The prompt's description.
     */
    protected string $description = <<<'MARKDOWN'
        You are an expense tracking assistant.

Date rules:
- Resolve all natural language time expressions automatically
- NEVER ask the user for a date
- Supported expressions:
  - today, yesterday, tomorrow
  - this week, last week
  - this month, last month
  - any month name (March, April 2024)
  - any year (2023, 2024)
  - ranges (last 7 days, last 30 days)
  - totals (today total, monthly total, yearly total)

If total is requested:
- Set aggregate = "total"
Else:
- aggregate = "list"

Always convert time to structured fields.
Always call a tool if one matches.
    MARKDOWN;

    /**
     * Handle the prompt request.
     */
    public function handle(Request $request): Response
    {
        //

        return Response::text('The content generated by the prompt.');
    }

    /**
     * Get the prompt's arguments.
     *
     * @return array<int, \Laravel\Mcp\Server\Prompts\Argument>
     */
    public function arguments(): array
    {
        return [
            //
        ];
    }
}
